package com.qb.core.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.qb.core.dto.QuestionDTO;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.List;

/**
 * Generates interview prep PDF using OpenPDF (LGPL — free for commercial use).
 */
@Slf4j
@Service
public class PdfService {

    private static final Font TITLE_FONT    = new Font(Font.HELVETICA, 18, Font.BOLD, Color.WHITE);
    private static final Font HEADER_FONT   = new Font(Font.HELVETICA, 10, Font.BOLD, Color.WHITE);
    private static final Font BODY_FONT     = new Font(Font.HELVETICA, 10, Font.NORMAL, Color.DARK_GRAY);
    private static final Font MUTED_FONT    = new Font(Font.HELVETICA, 9, Font.NORMAL, new Color(100, 100, 100));
    private static final Color DARK_BG      = new Color(15, 15, 15);
    private static final Color ACCENT_CYAN  = new Color(0, 240, 255);
    private static final Color ROW_ALT      = new Color(245, 245, 245);

    public byte[] generateQuestionListPdf(
            String candidateName,
            String companyName,
            String round,
            String interviewDate,
            List<QuestionDTO> questions
    ) {
        try (ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            Document doc = new Document(PageSize.A4, 40, 40, 50, 50);
            PdfWriter.getInstance(doc, out);
            doc.open();

            // ── Header ──────────────────────────────────────────────
            PdfPTable header = new PdfPTable(1);
            header.setWidthPercentage(100);
            PdfPCell titleCell = new PdfPCell();
            titleCell.setBackgroundColor(DARK_BG);
            titleCell.setPadding(16);
            titleCell.setBorder(Rectangle.NO_BORDER);

            Paragraph title = new Paragraph("Interview Prep — Question Bank", TITLE_FONT);
            title.setAlignment(Element.ALIGN_LEFT);
            titleCell.addElement(title);

            Paragraph meta = new Paragraph(
                    String.format("Candidate: %s  |  Company: %s  |  Round: %s  |  Date: %s",
                            candidateName, companyName, round.toUpperCase(), interviewDate),
                    new Font(Font.HELVETICA, 9, Font.NORMAL, ACCENT_CYAN)
            );
            titleCell.addElement(meta);
            header.addCell(titleCell);
            doc.add(header);
            doc.add(Chunk.NEWLINE);

            // ── Questions Table ──────────────────────────────────────
            PdfPTable table = new PdfPTable(new float[]{0.5f, 4f, 1.2f, 1.2f});
            table.setWidthPercentage(100);
            table.setSpacingBefore(8);

            addHeaderCell(table, "#");
            addHeaderCell(table, "Question");
            addHeaderCell(table, "Category");
            addHeaderCell(table, "Importance");

            for (int i = 0; i < questions.size(); i++) {
                QuestionDTO q = questions.get(i);
                Color rowBg = (i % 2 == 0) ? Color.WHITE : ROW_ALT;

                addBodyCell(table, String.valueOf(i + 1), rowBg, MUTED_FONT);
                addBodyCell(table, q.text(), rowBg, BODY_FONT);
                addBodyCell(table, q.category() != null ? q.category() : "General", rowBg, MUTED_FONT);
                addBodyCell(table, q.relevancyLabel() != null ? q.relevancyLabel() : "—", rowBg, MUTED_FONT);
            }

            doc.add(table);

            // ── Footer ───────────────────────────────────────────────
            doc.add(Chunk.NEWLINE);
            Paragraph footer = new Paragraph(
                    String.format("Total: %d questions  |  Generated by QuestionBank", questions.size()),
                    MUTED_FONT
            );
            footer.setAlignment(Element.ALIGN_RIGHT);
            doc.add(footer);

            doc.close();
            return out.toByteArray();

        } catch (Exception e) {
            log.error("PDF generation failed", e);
            throw new RuntimeException("Failed to generate PDF: " + e.getMessage(), e);
        }
    }

    private void addHeaderCell(PdfPTable table, String text) {
        PdfPCell cell = new PdfPCell(new Phrase(text, HEADER_FONT));
        cell.setBackgroundColor(DARK_BG);
        cell.setPadding(8);
        cell.setBorderColor(new Color(50, 50, 50));
        table.addCell(cell);
    }

    private void addBodyCell(PdfPTable table, String text, Color bg, Font font) {
        PdfPCell cell = new PdfPCell(new Phrase(text, font));
        cell.setBackgroundColor(bg);
        cell.setPadding(7);
        cell.setBorderColor(new Color(220, 220, 220));
        table.addCell(cell);
    }
}
